-- GENERATED by scripts/generate-catalog-sql.ts from src/progression. Do not edit by hand.
insert into public.missions (id, period, label, metric, target, reward) values
  ('daily_win_2', 'daily', 'Gagner 2 parties', 'wins', 2, '{"xp":60}'::jsonb),
  ('daily_capture_3', 'daily', 'Effectuer 3 captures', 'captures', 3, '{"xp":40}'::jsonb),
  ('daily_friend_1', 'daily', 'Jouer avec un ami', 'matchesWithFriend', 1, '{"xp":40}'::jsonb),
  ('daily_gifts_2', 'daily', 'Envoyer 2 cadeaux', 'giftsSent', 2, '{"xp":20}'::jsonb),
  ('daily_complete_1', 'daily', 'Terminer une partie', 'matchesCompleted', 1, '{"xp":20}'::jsonb),
  ('daily_spawn_5', 'daily', 'Sortir 5 pions', 'pawnsSpawned', 5, '{"xp":30}'::jsonb),
  ('weekly_win_10', 'weekly', 'Gagner 10 parties', 'wins', 10, '{"xp":300,"fragments":[{"itemId":"samurai","count":1}]}'::jsonb),
  ('weekly_finish_40', 'weekly', 'Amener 40 pions au centre', 'pawnsFinished', 40, '{"xp":250}'::jsonb)
on conflict (id) do update set period = excluded.period, label = excluded.label,
  metric = excluded.metric, target = excluded.target, reward = excluded.reward;

insert into public.achievements (id, label, metric, target, reward) values
  ('first_win', 'Première victoire', 'wins', 1, '{"xp":50}'::jsonb),
  ('matches_100', '100 parties', 'matchesCompleted', 100, '{"xp":500,"titleId":"veteran"}'::jsonb),
  ('captures_100', '100 captures', 'captures', 100, '{"xp":300,"titleId":"hunter"}'::jsonb),
  ('streak_5', 'Série de 5 victoires', 'bestWinStreak', 5, '{"xp":250}'::jsonb),
  ('perfect_finish', 'Amener ses 4 pions au centre', 'perfectFinishes', 1, '{"xp":50}'::jsonb),
  ('pacifist', 'Gagner sans capturer', 'winsWithoutCapture', 1, '{"xp":100,"titleId":"pacifist"}'::jsonb)
on conflict (id) do update set label = excluded.label, metric = excluded.metric,
  target = excluded.target, reward = excluded.reward;
