import {CATALOG} from '../src/inventory/catalog.ts';

const quote = (value: string | null) =>
  value === null ? 'null' : `'${value.replace(/'/g, "''")}'`;

/** SQL seed for public.items, generated from the TypeScript catalogue. */
export function catalogSeedSql(): string {
  const rows = CATALOG.map(
    item =>
      `  (${quote(item.id)}, ${quote(item.category)}, ${quote(item.themeId)}, ${quote(item.name)}, ` +
      `${quote(item.rarity)}, ${quote(item.acquisition)}, ${quote(item.price?.currency ?? null)}, ` +
      `${item.price ? String(item.price.amount) : 'null'})`
  );
  return [
    '-- GENERATED by scripts/generate-catalog-sql.ts from src/inventory/catalog.ts. Do not edit by hand.',
    'insert into public.items (id, category, theme_id, name, rarity, acquisition, price_currency, price_amount) values',
    rows.join(',\n'),
    'on conflict (id) do update set',
    '  category = excluded.category, theme_id = excluded.theme_id, name = excluded.name,',
    '  rarity = excluded.rarity, acquisition = excluded.acquisition,',
    '  price_currency = excluded.price_currency, price_amount = excluded.price_amount;',
    '',
  ].join('\n');
}

export const CATALOG_MIGRATION =
  'supabase/migrations/20260923000500_catalog_seed.sql';
