import {CATALOG} from '../src/inventory/catalog.ts';
import {ACHIEVEMENTS} from '../src/progression/achievements.ts';
import {MISSIONS} from '../src/progression/missions.ts';

const quote = (value: string | null) =>
  value === null ? 'null' : `'${value.replace(/'/g, "''")}'`;

/** SQL seed for public.items, generated from the TypeScript catalogue. */
export function catalogSeedSql(): string {
  const rows = CATALOG.map(
    item =>
      `  (${quote(item.id)}, ${quote(item.category)}, ${quote(item.themeId)}, ${quote(item.name)}, ` +
      `${quote(item.rarity)}, ${quote(item.acquisition)}, ${quote(item.price?.currency ?? null)}, ` +
      `${item.price ? String(item.price.amount) : 'null'})`
  );
  return [
    '-- GENERATED by scripts/generate-catalog-sql.ts from src/inventory/catalog.ts. Do not edit by hand.',
    'insert into public.items (id, category, theme_id, name, rarity, acquisition, price_currency, price_amount) values',
    rows.join(',\n'),
    'on conflict (id) do update set',
    '  category = excluded.category, theme_id = excluded.theme_id, name = excluded.name,',
    '  rarity = excluded.rarity, acquisition = excluded.acquisition,',
    '  price_currency = excluded.price_currency, price_amount = excluded.price_amount;',
    '',
  ].join('\n');
}

export const CATALOG_MIGRATION =
  'supabase/migrations/20260923000500_catalog_seed.sql';

const json = (value: unknown) => quote(JSON.stringify(value)) + '::jsonb';

/** SQL seed for public.missions and public.achievements. */
export function progressionSeedSql(): string {
  const missions = MISSIONS.map(
    m =>
      `  (${quote(m.id)}, ${quote(m.period)}, ${quote(m.label)}, ${quote(m.metric)}, ${m.target}, ${json(m.reward)})`
  );
  const achievements = ACHIEVEMENTS.map(
    a =>
      `  (${quote(a.id)}, ${quote(a.label)}, ${quote(a.metric)}, ${a.target}, ${json(a.reward)})`
  );
  return [
    '-- GENERATED by scripts/generate-catalog-sql.ts from src/progression. Do not edit by hand.',
    'insert into public.missions (id, period, label, metric, target, reward) values',
    missions.join(',\n'),
    'on conflict (id) do update set period = excluded.period, label = excluded.label,',
    '  metric = excluded.metric, target = excluded.target, reward = excluded.reward;',
    '',
    'insert into public.achievements (id, label, metric, target, reward) values',
    achievements.join(',\n'),
    'on conflict (id) do update set label = excluded.label, metric = excluded.metric,',
    '  target = excluded.target, reward = excluded.reward;',
    '',
  ].join('\n');
}

export const PROGRESSION_MIGRATION =
  'supabase/migrations/20260923000710_progression_seed.sql';
